import { Router } from "express";
import userRoutes from "./user.routes.js";
import bookingRoutes from "./booking.routes.js";
import serviceRoutes from "./service.routes.js";
import employeeRoutes from "./employee.routes.js";
// import invoiceRoutes from "./invoice.routes.js";
import taxInvoiceRoutes from "./taxInvoice.routes.js";
import proformaRoutes from "./proforma.routes.js";
import leadRoutes from "./lead.routes.js";
import adminRoutes from "./admin.routes.js";
import paymentRoutes from "./payment.routes.js";
import emailRoutes from "./email.routes.js";
import welcomeRoutes from "./welcome.routes.js";
import healthRoutes from "./health.routes.js";
import { authenticateUser } from "#middlewares/authMiddleware.js";
import { contextMiddleware } from "#middlewares/context.middleware.js";

const router = Router();
router.use("/health", healthRoutes);
router.use("/user", userRoutes);
router.use(authenticateUser);
router.use(contextMiddleware);
router.use("/booking", bookingRoutes);
router.use("/services", serviceRoutes);
router.use("/employee", employeeRoutes);
router.use("/taxinvoice", taxInvoiceRoutes);
router.use("/proforma", proformaRoutes);
router.use("/leads", leadRoutes);
router.use("/admin", adminRoutes);
router.use("/payments", paymentRoutes);
router.use("/email", emailRoutes);
router.use("/mail", welcomeRoutes);

export default router;
